index:
    path: /
    controller: App\Controller\PersonnelController::personnel

bareme:
    path: /bareme/import
    controller: App\Controller\BaremeController::import_form

connexion:
    path: /connexion
    controller: App\Controller\UserController::seConnecterForm